services:
  languagetool:
    extends:
      file: ./docker/services.compose.yml
      service: languagetool

  llm:
    extends:
      file: ./docker/services.compose.yml
      service: llm

  textmate-backend:
    extends:
      file: ./docker/services.compose.yml
      service: textmate-backend
    ports:
      - "8000:8000"